name: Docker Build & Push

on:
  push:
    tags:
      - 'v*.*.*'  # déclenche uniquement sur les tags comme v1.0.0, v1.1.0, etc.

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Debug : vérifier que le secret est bien présent
      - name: Debug MY_TOKEN
        run: |
          if [ -z "${{ secrets.MY_TOKEN }}" ]; then
            echo "MY_TOKEN secret is not set"
            exit 1
          else
            echo "MY_TOKEN is set"
          fi

      # 3️⃣ Nettoyer Docker (au cas où)
      - name: Logout Docker (clean)
        run: docker logout ghcr.io || true

      # 4️⃣ Se connecter à GHCR avec le PAT
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_TOKEN }}

      # 5️⃣ Setup QEMU pour multi-architecture (optionnel)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # 6️⃣ Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 7️⃣ Build et push l’image Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/ci-cd_mariama:${{ github.ref_name }}
