name: Docker Build & Push

on:
  push:
    tags:
      - 'v*.*.*'  # déclenche sur les tags comme v1.0.0, v1.1.0, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code
      - uses: actions/checkout@v4

      # 2️⃣ Se connecter à GHCR avec le PAT
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # 3️⃣ Setup QEMU (optionnel pour multi-arch)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # 4️⃣ Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 5️⃣ Construire et pousser l’image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/ci-cd_mariama:${{ github.ref_name }}
